途中コード確認依頼
masatakamoroe/next_app pull request #3
Opened 2021-02-05 16:36 UTC by masatakamoroe

[WIP]
コード確認宜しくお願いします。
途中経過です。
現在templatesまで書き進めてみました。
進め方、書き方は問題ないか確認していただきたいです。

2021-02-08 09:59 UTC, tsurutan requested changes
ご確認お願いします。

2021-02-08 09:59 UTC, tsurutan commented on src/components/atoms/Checkbox/styles.module.css
> +color: #43425D;
[must]
こちらインデントがずれています。
VSCodeではcssなどのプラグインを入れ、保存時にフォーマットをかけることができるので試してみてください。

2021-02-08 09:59 UTC, tsurutan commented on src/components/atoms/Label/styles.module.css
> +  }
[must]
こちらもインデントがずれています。

2021-02-08 09:59 UTC, tsurutan commented on src/components/atoms/SecondaryButton/index.tsx
> +  export default PrimaryButton;
[must]
インデントがずれています。

2021-02-08 09:59 UTC, tsurutan commented on src/pages/index.tsx
> +      <HomeTemplate></HomeTemplate>
[imo]
タグの中に値が入っていない場合は

```
<HomeTemplate />
```
と簡潔に書けるのでこちらにしましょう。

2021-02-08 09:59 UTC, tsurutan commented on src/pages/index.tsx
> +import HomeTemplate from "../components/templates/HomeTemplate"
[imo]
相対パスになっているので絶対パスにしましょう。

2021-02-08 10:32 UTC, masatakamoroe commented on src/pages/index.tsx
> +import HomeTemplate from "../components/templates/HomeTemplate"
[ask]
HomeTemplateを相対パスから絶対パスに変更しました。
styleディレクトリのHome.module.cssはsrc配下と別なので一旦このままでもよろしいでしょうか？

2021-02-08 10:32 UTC, masatakamoroe commented on src/pages/index.tsx
> +      <HomeTemplate></HomeTemplate>
変更しました。

2021-02-08 10:32 UTC, masatakamoroe commented on src/components/atoms/SecondaryButton/index.tsx
> +  export default PrimaryButton;
変更しました。

2021-02-08 10:32 UTC, masatakamoroe commented on src/components/atoms/Label/styles.module.css
> +  }
変更しました。

2021-02-08 10:32 UTC, masatakamoroe commented on src/components/atoms/Checkbox/styles.module.css
> +color: #43425D;
変更しました。

2021-02-09 09:56 UTC, tsurutan requested changes

2021-02-09 09:56 UTC, tsurutan commented on src/components/atoms/PrimaryButton/styles.module.css
> +    margin: 10px 30px 50px;
[imo]
今はまだ良いかもしれませんが、今後スマホにもデザインを対応をさせたいときに px ではなく rem を使用するとレスポンシブ対応ができるのでおすすめです。
https://web-roku.com/css-rem

2021-02-09 09:56 UTC, tsurutan commented on src/components/atoms/SecondaryButton/styles.module.css
> +    background:white;
[imo]
現在 css を使用していますが、css だと `;` や `{` `}` を書かなくてはならないため、少し冗長になります。
これらを省略できる sass というものがあるのでこちらを使用してみましょう。

2021-02-09 09:56 UTC, tsurutan commented on src/components/atoms/SecondaryButton/styles.module.css
> +    background:white;
[imo]
色など他の箇所でも使用する値は、変数として一つのファイルに纏めたほうが管理しやすくなります。

`src/components/global.module.sass` に

```sass
$green: #123123
```

のような感じで色に関する変数を作成し、この色を読み込むところで

```sass
@import "../../global.module.sass"

.button
  color: $green
```

のように書くとメンテナンスしやすくなると思います。

(上の例はそのまま書いても動かない可能性があるので、適宜修正してください)

2021-02-09 09:56 UTC, tsurutan commented on styles/Home.module.css
>  .container {
[imo]
こちらのファイルは使用していないと思うので削除しましょう。
それぞれコンポーネントに対応するstylesは `コンポーネント名/styles.module.sass` になっているため。

2021-02-09 17:58 UTC, masatakamoroe commented on src/components/atoms/SecondaryButton/styles.module.css
> +    background:white;
変更しました。

2021-02-09 17:59 UTC, masatakamoroe commented on styles/Home.module.css
>  .container {
削除しました。

2021-02-09 19:33 UTC, masatakamoroe commented on src/components/atoms/PrimaryButton/styles.module.css
> +    margin: 10px 30px 50px;
remに変更しました。

2021-02-10 02:40 UTC, tsurutan requested changes

2021-02-10 02:40 UTC, tsurutan commented on src/components/atoms/SecondaryButton/styles.module.sass
> +    background:white
[nits]
`:` の横にスペースがありません。

2021-02-10 02:40 UTC, tsurutan commented on src/components/atoms/SecondaryButton/styles.module.sass
> +    font-family: 'Athelas',sans-serif
[imo]
このフォントも変数にまとめてしまいましょう。

2021-02-10 02:40 UTC, tsurutan commented on src/components/organisms/ImputForm/index.tsx
> +import TextboxWithLabel from "components/molecules/TextboxWithLabel";
[imo]
`components/molecules` からインポートするようにしましょう。

2021-02-10 02:40 UTC, tsurutan commented on src/components/templates/HomeTemplate/index.tsx
> +import CheckButton from "components/organisms/CheckButton";
[imo]

`components/organisms` からインポートするようにしましょう。

2021-02-10 02:40 UTC, tsurutan commented on src/pages/_app.tsx
> +import * as React from 'react'
[nits]

```
import React from 'react'
```
で書けるかと思います。

2021-02-10 04:40 UTC, masatakamoroe commented on src/pages/_app.tsx
> +import * as React from 'react'
変更しました。

2021-02-10 04:40 UTC, masatakamoroe commented on src/components/templates/HomeTemplate/index.tsx
> +import CheckButton from "components/organisms/CheckButton";
変更しました。

2021-02-10 04:40 UTC, masatakamoroe commented on src/components/organisms/ImputForm/index.tsx
> +import TextboxWithLabel from "components/molecules/TextboxWithLabel";
変更しました。

2021-02-10 04:40 UTC, masatakamoroe commented on src/components/atoms/SecondaryButton/styles.module.sass
> +    font-family: 'Athelas',sans-serif
変更完了しました。

2021-02-10 04:40 UTC, masatakamoroe commented on src/components/atoms/SecondaryButton/styles.module.sass
> +    background:white
変更しました。

2021-02-10 12:16 UTC, masatakamoroe commented on src/components/templates/HomeTemplate/index.tsx
> +import CheckButton from "components/organisms/CheckButton";
[ask]
Home TemplateをOrganismsへ移行し名前をTableと書き換えましたが
あまりしっくりきていません。Mainの方がよろしいでしょうか？

2021-02-10 13:16 UTC, tsurutan requested changes

2021-02-10 13:16 UTC, tsurutan commented on src/components/atoms/SecondaryButton/styles.module.sass
> +    font-family: 'Athelas',sans-serif
こちらまとまっておりません！
色と同じように $のついた変数としてまとめましょう

2021-02-10 13:16 UTC, tsurutan commented on src/components/templates/HomeTemplate/index.tsx
> +export default HomeTemplate;
[imo]
細かいですが、githubで禁止マークみたいなものが表示されているのはファイルの末尾に改行がないためであり、末尾には改行を入れるようにしましょう。
他のファイルも同様に対応お願いします。

2021-02-11 02:56 UTC, tsurutan requested changes

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/CheckButton/index.tsx
> +import CheckboxWithLabel from "components/molecules/CheckboxWithLabel";
[imo]
components/molecules からインポートするようにしましょう。

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/CheckboxWithLabel/index.tsx
> +import Checkbox from "components/atoms/Checkbox";
[imo]
components/atoms からインポートするようにしましょう。

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/Header/index.tsx
> +import Label from "components/atoms/Label";
同上

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/Header/styles.module.sass
> +    font-family: 'Athelas',sans-serif
変数を使用しましょう

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/ImputForm/index.tsx
> +import TextboxWithLabel from "components/molecules/TextboxWithLabel";
同上

2021-02-11 02:56 UTC, tsurutan commented on src/components/molecules/TextboxWithLabel/index.tsx
> +import Textbox from "components/atoms/Textbox";
同上

2021-02-11 02:56 UTC, tsurutan commented on src/components/organisms/Table/index.tsx
> +import CheckButton from "components/molecules/CheckButton";
同上

2021-02-11 02:56 UTC, tsurutan commented on src/components/templates/HomeTemplate/index.tsx
> +import Table from "components/organisms/Table";
同上

2021-02-11 02:56 UTC, tsurutan commented on src/pages/index.tsx
> +import HomeTemplate from "components/templates/HomeTemplate";
同上

2021-02-11 09:01 UTC, tsurutan requested changes

2021-02-11 09:01 UTC, tsurutan commented on src/components/molecules/TextboxWithLabel/styles.module.sass
> +    display: flex-end
[must]
displayの値に flex-endはないためこちらは誤りだと思います。
https://www.w3schools.com/cssref/pr_class_display.asp

2021-02-12 00:52 UTC, tsurutan approved these changes
LGTM!

2021-02-12 01:46 UTC, merged