Editorページのデザイン作成
masatakamoroe/next_app pull request #7
Opened 2021-02-22 12:30 UTC by masatakamoroe

Editorページのデザイン作成が完了しました。
ご確認宜しくお願い致します。

2021-02-23 01:38 UTC, tsurutan requested changes

2021-02-23 01:38 UTC, tsurutan commented on src/components/atoms/SimpleDatePicker/index.tsx
> +    const [startDate] = useState<Date | null | undefined>(new Date());
[ask]
こちらは
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-datepicker/index.d.ts#L143
ここで型定義がされているのですが、これを参考に

```ts
const [startDate, setStartDate] = useStgate<Date | null>(new Date());
```

とできないでしょうか？

2021-02-23 01:49 UTC, masatakamoroe commented on src/components/atoms/SimpleDatePicker/index.tsx
> +    const [startDate] = useState<Date | null | undefined>(new Date());
はい、そこで悩んでいたポイントで、
上記の内容も試みましたが、
dateがts.(2345)のエラーになってしまいます。

2021-02-23 06:45 UTC, masatakamoroe commented on src/components/atoms/SimpleDatePicker/index.tsx
> +    const [startDate] = useState<Date | null | undefined>(new Date());
node_modulesに入っている@typesから
react-datepickerへ行き、
date: Date | [Date,Date]|/* for selectsRange */ null,
になっているところを
date: Date | /* for selectsRange */ null,
へ変更し
こちらも
const [startDate, setStartDate] = useStgate<Date | null>(new Date());
へ変更すると問題なく出来ました！

2021-02-23 14:13 UTC, tsurutan requested changes

2021-02-23 14:13 UTC, tsurutan commented on src/components/atoms/SimpleDatePicker/index.tsx
> +            onChange={date => setStartDate(date)}
[imo]
node_modulesは基本的に管理外のコードのため、node_modulesは基本変更しないでください！
今回渡ってきている date が  [Date, Date] という型とみなされる可能性がありますが、これを
date: Date => setStartDate(date)
とすることで除外することができるので、こちら試してみてください。

2021-02-23 14:13 UTC, tsurutan commented on src/pages/Editor.tsx
> +import { EditorTemplate } from "components/templates";
[imo]
next.jsではpages配下のディレクトリ名に沿ってページを作成してしまうため、pages配下は例外として小文字のスネークケースでディレクトリ名を記入してください Editor.tsx -> editor.tsx

2021-02-24 13:23 UTC, tsurutan approved these changes
LGTM!

2021-02-24 13:28 UTC, merged